import { Container, mantineHtmlProps, MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CommonGrounds",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      {...mantineHtmlProps}
    >
      <head />
      {/* For Dark/Light Mode. Visit: https://mantine.dev/theming/color-schemes/  */}
      <body>
        <MantineProvider>
          <Container fluid p={0}>
            {children}
          </Container>
        </MantineProvider>
      </body>
    </html>
  );
}
