import Navbar from '@/components/navbar';
import ThemeProvider from '@/components/theme-provider';
import {
  Container,
  createTheme,
  mantineHtmlProps,
  MantineProvider,
} from '@mantine/core';
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import { ModalsProvider } from '@mantine/modals';
import { Notifications } from '@mantine/notifications';
import '@mantine/notifications/styles.css';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const theme = createTheme({
  primaryColor: 'blue',

  colors: {
    dark: [
      '#FFFFFF',
      '#F8FAFC',
      '#F1F5F9',
      '#E2E8F0',
      '#CBD5E1',
      '#475569',
      '#334155',
      '#1E293B',
      '#111827',
      '#000000',
    ],
  },
});

export const metadata: Metadata = {
  title: 'CommonGrounds',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: LayoutProps<'/'>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head />

      <body>
        <MantineProvider
          theme={theme}
          defaultColorScheme="light"
        >
          <ThemeProvider>
            <ModalsProvider>
              <Notifications />

              <Container fluid p={0}>
                <Navbar>{children}</Navbar>
              </Container>
            </ModalsProvider>
          </ThemeProvider>
        </MantineProvider>
      </body>
    </html>
  );
}